#!/bin/bash

export NUM_OF_REDUCERS_JOB1=1
export NUM_OF_REDUCERS_JOB2=1
export DATA_SIZE=small

#SBATCH --partition=debug
#SBATCH --time=00:57:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
##SBATCH --constraint=CPU-L5520
#SBATCH --exclusive
##SBATCH --mem=24000
##SBATCH --mem-per-cpu=4000
#SBATCH --job-name=ankitkap
#SBATCH --output=test_ankitkap.out
#SBATCH --mail-user=ankitkap@buffalo.edu
#SBATCH --mail-type=ALL
##SBATCH --requeue
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.
#
#This SLURM script is modified version of the SDSC script
# found in /util/myhadoop/myHadoop-0.30b/examples.
# CDC Nov 5, 2014
#
echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

echo "working directory = "$SLURM_SUBMIT_DIR
module load java/1.6.0_22
module load hadoop/2.5.1
module load myhadoop/0.30b
module list
echo "MH_HOME="$MH_HOME
echo "HADOOP_HOME="$HADOOP_HOME
echo "JAVA_HOME="$JAVA_HOME
echo "Setting HADOOP to use SLURMTMPDIR on the local disk"
export MH_SCRATCH_DIR=$SLURMTMPDIR
echo "MH_SCRATCH_DIR="$MH_SCRATCH_DIR
#### Set this to the directory where Hadoop configs should be generated
# Don't change the name of this variable (HADOOP_CONF_DIR) as it is
# required by Hadoop - all config files will be picked up from here
#
# Make sure that this is accessible to all nodes
export HADOOP_CONF_DIR=/gpfs/scratch/ankitkap/configs/config-$SLURM_JOBID
echo "MyHadoop config directory="$HADOOP_CONF_DIR
### Set up the configuration
# Make sure number of nodes is the same as what you have requested from PBS
# usage: $myhadoop-configure.sh -h
# this is the non-persistent mode
NPROCS=`srun --nodes=${SLURM_NNODES} bash -c 'hostname' |wc -l`
echo "-------Set up the configurations for myHadoop"
$MH_HOME/bin/myhadoop-configure.sh 
echo "-------Start hdfs and yarn ---"
$HADOOP_HOME/sbin/start-all.sh
#### Format HDFS, if this is the first time or not a persistent instance
echo "-------Show Report ---"
$HADOOP_HOME/bin/hadoop dfsadmin -report
echo "-------make directory ---"

# MAKE THIS AS $1 later
export VERYSMALL_INPUT_PATH=/user/ankitkap/StockVolatility/verysmall/*.csv
export SMALL_INPUT_PATH=/gpfs/courses/cse587/spring2015/data/hw1/small/*.csv
export MEDIUM_INPUT_PATH=/gpfs/courses/cse587/spring2015/data/hw1/medium/*.csv
export LARGE_INPUT_PATH=/gpfs/courses/cse587/spring2015/data/hw1/large/*.csv
export OUTPUT_FILE_NAME=Output
export MAIN_OUTPUT_FILE_NAME=./outputs/myoutput-$SLURM_JOBID

$HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR dfs -mkdir /data
echo "-------copy file to hdfs ---"
$HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR dfs -put $1/*.csv /data 
echo "-------list directory ---"
$HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR dfs -ls /data
echo "-------do wordcount of file ---"
$HADOOP_HOME/bin/hadoop --config $HADOOP_CONF_DIR jar /gpfs/user/ankitkap/StockVolatility/StockVolatility_feb25.jar /data $OUTPUT_FILE_NAME $NUM_OF_REDUCERS_JOB1 $NUM_OF_REDUCERS_JOB2
echo "-------list output ---"
$HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR dfs -ls $OUTPUT_FILE_NAME
echo "-------Get outout ---"
$HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR dfs -get $OUTPUT_FILE_NAME $2

echo "-------Stop hdfs and yarn ---"
$HADOOP_HOME/sbin/stop-all.sh

#### Clean up the working directories after job completion
$MH_HOME/bin/myhadoop-cleanup.sh
